# Generated by Django 6.0.2 on 2026-04-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=None, verbose_name=''),
        ),
    ]
